name: Cpp

on:
    push:
      branches:
        - '**'

jobs:
  cpp_run:
    name: Cpp
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
            auto-update-conda: true
            auto-activate-base: true
            activate-environment: ""

      - name: Create conda environment
        run: |
          conda create -n "stan" python=${{matrix.python-version}} cmdstanpy -c conda-forge

      - name: CmdStanPy and CmdStan versions
        run: |
          conda activate stan
          python -c 'import cmdstanpy;print("cmdstanpy version: {}".format(cmdstanpy.__version__))'
          python -c 'import cmdstanpy;print("cmdstan version: {}".format(cmdstanpy.cmdstan_path()))'


      - name: CmdStanPy seed test
        run: |
          conda activate stan
          python run_pystan.py
