name: Cpp

on:
    push:
      branches:
        - '**'

jobs:
  cpp_equality:
    name: Cpp
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
            auto-activate-base: true
            activate-environment: ""

      - name: Create conda environment
        run: |
          conda create -n "stan" python=3.9 cmdstanpy -c conda-forge

      - name: CmdStanPy and CmdStan versions
        run: |
          python -c 'import cmdstanpy;print("cmdstanpy version: {}".format(cmdstanpy.__version__))'
          python -c 'import cmdstanpy;print("cmdstan version: {}".format(cmdstanpy.cmdstan_path()))'


      - name: CmdStanPy seed test
        run: |
          python run_pystan.py
